# fly.toml app configuration file generated for 1-primetime on 2025-12-14T20:08:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '1-primetime'
primary_region = 'fra'

[build]
  [build.args]
    GO_VERSION = '1.25.4'

[env]
  PORT = '2002'

[[services]]
  internal_port = 2002
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 10002
    handlers = []

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
